[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/contact"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling configuration
[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'" 